### ISSUE TITLE
Experimental pretrained checkpoint request

### ISSUE THREAD

**Issue by YtengTan** [Gwinhen/HardBeat#1]
Hello,

Thanks for the open source of your amazing work HardBeat.

It would be great if you could also provide your experimental pretrained models.

Thanks!

**Comment by Gwinhen** [comment]
Thank you for being interested in our work!

Please find the model checkpoints used in our paper on [Google Drive](https://drive.google.com/drive/folders/1spa0A2Tj4c7OpqTagdRzeslmahKIaBEh?usp=sharing).

**Comment by YtengTan** [comment]
> Thank you for being interested in our work!
> 
> Please find the model checkpoints used in our paper on [Google Drive](https://drive.google.com/drive/folders/1spa0A2Tj4c7OpqTagdRzeslmahKIaBEh?usp=sharing).

Thank you for sharing!
